apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-automation
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      nodeName:
          k3s-131
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:2024.8.2
          ports:
            - containerPort: 8123
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "wget -O https://get.hacs.xyz | bash -" ]
          volumeMounts:
            - mountPath: /config
              name: config
#            - mountPath: /config/configuration.yaml
#              subPath: configuration.yaml
#              name: configmap-file-india
#            - mountPath: /config/automations.yaml
#              subPath: automations.yaml
#              name: configmap-file-india
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-pvc       


