apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
  namespace: home-automation
  labels:
    recurring-job-group.longhorn.io/every-week: enabled
    recurring-job.longhorn.io/source: enabled 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
