apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: proxmox-csi-sops
    namespace: proxmox-csi
spec:
    secretTemplates:
        - name: proxmox-csi-config
          labels:
            app: csi-config
          stringData:
            config.yaml: ENC[AES256_GCM,data:5HObNMjem5KQA1VV0LlBvVUk44oKafDDs/zyL38NpnnvK9nJg4v3WSfHV4FjHh3hBCoJTPDneiDVsbEsB+Kes5NU9PM9SKXTKWktPnL8HqGxJY3Txs5jKtD1vhlHvi+CPyot99YbjMj3E68QedG1sThesJi1S37i9opDwzZ06P83MSy3reKOl+dIheib+7PqJaaQUrqgmgjTNsVuLgHC1Itq/bwh1hNukY+7XHtGR51scJbt22pQCvGSibWuQpsP0U/bIWszNDiOPogj78+V5A==,iv:Fr4Mtox/1qLlDLtHAnFOrSpDN70uuSK8e0P1fHP/0e4=,tag:2Hq5Wn6JgEm+cNRQIUiiPg==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN1EzTThWTHlMMUFoSjR4
            MmxpRS9TUnpWSGp5QmVkdHhCUHZ0Sk91R0JNCjk2ZHJPL2JTTUw0QUhLN1prNDIx
            TlhQcVZqcEVac3JHMVZsdGNrSU11QU0KLS0tIE1Pc1VleEJtNGRTRXZremJoUkdY
            cGdocE1aVitjVHFTUlVna09jTU80VDAKcH9Cibkzti5e6vyDIOF9Md9NW+Ri4ewk
            AHi2by8gxBohmE3kyZMgdBcbUz6TrYmvC9DjDUZ0OWxmE8XKwyxtRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T17:40:01Z"
    mac: ENC[AES256_GCM,data:tLdq8+/AdKzLaw9J/g4Cg6F5JJK73q9OwBiAyDMUFPdVYLg89Fj6yypYy7bDt5NpX+N4uVvgRlosJU5NIXv66BJz2gnRsHNfoN/37W3ujfKv+EdCqNe2W50Cqq16lm37PqXyDe1C3Ar6V+VDjbooNyCYG40KEPWPb6B8THXgqT8=,iv:mLeNnfSZo9exhOUoHoI5XK3kIUGsOhgz7/05xXZo/GU=,tag:1kbngNM9i1W4t02xynsOHQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
