apiVersion: ENC[AES256_GCM,data:r6dt2yaMDGSv3yCQ/yOEDFL8mSjpSS3344zm,iv:Xm+iqoxOHsJXpl0gjXPDGCMypG4OeIpLQgDgmzm5+tM=,tag:IPMpy1CpfJ1R/1a1f+u2jA==,type:str]
kind: ENC[AES256_GCM,data:IPesyHiec5VPkA==,iv:LoBt7kRwLrxluDs2Z1i1Fbdr/ScwBTd6+UwCTPNNGSU=,tag:VpC94l9cX1cdOAhkyBNYsQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZBzEeykGDvDxCL/YeWaQCg==,iv:7jcyAEnKfbLNUywicMk2JFFaqBAb+6eSoniB4kW2HJU=,tag:q0v50aAGm324I89RaejcRA==,type:str]
    namespace: ENC[AES256_GCM,data:hIBziGiJYR+h6OE=,iv:IU20U+elOXGCbt5xl5HtyLSWj/h35mI7J7rzao7VsF0=,tag:I3wxdYzOkItGDVWzjbjLIA==,type:str]
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:sV1vUHM2W7l9ImYsCpjrPZAe,iv:A9WmuW0jsvjwk5ManqqXafPWOzvRg1XoiqqJy6X2HpI=,tag:RCkVHJkGyao7yedc7x3YHQ==,type:str]
          labels:
            app: ENC[AES256_GCM,data:ufGO/i/kOuimzQ==,iv:yLHh8xb89qhpcNpoKKHcuwNmyHpp9VmIVTYlLHRazaQ=,tag:PkntAxu4J9NavceWoDH8HA==,type:str]
          stringData:
            config.yaml: ENC[AES256_GCM,data:gZquRTl7WGlUMsT/pvniT0rEk/QfCzZ9gouQU6eFswDzrLvhjNEMbx+9CB21shnXspLBPOXtnBaaPEhU3GwU78pfi8vWm8DNIXgXoWpgK9AOiEYIHQ8fSq6LfoSnS7gikSodMov5a/57gkB/nU6ZWZDpbv0UzM+YzB3FsuzyxVZg4suiEeGBO5ChImF6jc6FC5exhVEbWujLmLtHupcsLgJMLw7kzxCV5xGE+Qnb06VryWZJl1kH+WYNJog8lzrIg1jGLQneQQgI/IET+dsdSA==,iv:+CVAsPSuKEx/t/C6FSj1sgU56jTdNpQBXP0spdzV6GU=,tag:JPCBxxo3oXrFjQi8De3rpw==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SlBZTCswd0JLdWV1VzhL
            THJwMzRRcW9JM01EaEpMdEVaTXU0T0ZCMTJjCllzT00yNWIzR0hQMkxuT2RTSmd4
            dml1Q3pvRWlFSTRFYVc1MFNTcHM5U0EKLS0tIHp2QUE0amY5aTJEYmJCaWtvVHNP
            aWtkZVF4cGE0ck9QdkowV3pLWi85UDQKwTd8aMS2lf6v4y/R+SBOYaINSIy/fBvC
            fZcICWjONF720ABMDndfsn/ZMBHnyc+28bLDMHyt54JKN7xbVLvf2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T15:42:47Z"
    mac: ENC[AES256_GCM,data:X/dIj1WWBdTaYhxxRhq1ILGVdXUe+4Urqaql7c4X/pKl3ZmPA4HbEG2CVzYDhkkiOqobyTchJGc95sT4+5VddrOkrAi8pDNiMkk7MYYCmYjvlzmaMzvkoXV46bToo89ut1KLn/YZvVHPKLwAhsItDNN680yKS9VTVCQC4rmUOWA=,iv:x0lbpgD4Mkd8BU/2IbiMoT4mlX2tJGJyDXERFxu9gME=,tag:1Gj9C/T77GnxKrxurPkzvw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
