
{{- if .Values.registry.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry
  labels:
    app: registry
  annotations:
    {{- if .Values.registry.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.registry.ingress.className }}
    {{- end }}
spec:
  {{- if .Values.registry.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.registry.ingress.host }}
      secretName: {{ .Values.registry.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.registry.ingress.host }}
      http:
        paths:
          - path: {{ .Values.registry.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: registry
                port:
                  number: {{ .Values.registry.service.port }}
{{- end }}
