apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  type: {{ .Values.registry.service.type }}
  ports:
    - name: http
      port: {{ .Values.registry.service.port }}
      targetPort: {{ .Values.registry.port }}
  selector:
    app: registry
