{{- if .Values.registry.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  labels:
    app: registry
    {{- with .Values.registry.persistence.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.registry.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.registry.persistence.size }}
  {{- if .Values.registry.persistence.storageClassName }}
  storageClassName: {{ .Values.registry.persistence.storageClassName }}
  {{- end }}
{{- end }}
