- name: Install pip
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-kubernetes
    state: present
    update_cache: false
- name: Install helm if not exists
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  args:
    creates: /usr/local/bin/helm
