apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: proxmox-ccm-sops
    namespace: kube-system
spec:
    secretTemplates:
        - name: proxmox-csi-config
          labels:
            app: cloud-control-manager-config
          stringData:
            config.yaml: ENC[AES256_GCM,data:mAZSnOya5zRRmxS+7ojeahCo9MG2hJNuLua2ytpLwIXJ+6gUYpza669StJphZj96wEPSmcSFi8mkgYBX2OeIwGheV7xst7NLHuReHwcntMci4UWVz9vLCeOfMNwKKi/ArW8PdOrbNtk7cnNdtuNSAWMQSzAwcL+o9ul+5DtYKkOPzdJujiEP3H9nMV8/CdHP2m3fc8P7NZTKWTaso9cyAVcZpiS9K8DyxsI2BqcMwgwxA3XQuPc9oKMS17336zQ1UBBfiv4TeTYVqPToEP3ECw==,iv:GjFRvIzlz6JrjRxilajIAH47JgEndbk2tGMj7Hs+UbY=,tag:Z9Jvz+V9b7oBHVK1azx7VA==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TkF2eVJKV3FndlAwY2Zh
            dVVaZ0tFcTlWZ0pxVjl0RDVNeGQxdFJoZ0hZCmJyRCtQekx6Qm9ZV0I5SWIrckRG
            cVVxNzZIb1RkWFN1VW9QdlNua0lIQ00KLS0tIDJsblkzWVZ4YXAxK3BidVY1SXFV
            eGRNWmgzR2JlaVJDU1VRQUZ4YTVRUFkKyCfbf50It3JdOM0Tak0c/aZp4xh7hrBz
            qnDKItkBtfEocxRwiAHAcwM8LSDr5RPnB30y+ehYIgLYCrMQKEZ2og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T16:49:51Z"
    mac: ENC[AES256_GCM,data:7GBKLySlVNc9PgOZ1WfAQV1mxSpgpLPvvb4halZabpwE7r9MMWv1ZCnjXszCbSt2Bfan6q+0bt/Tig3N2wDtHwOzqKJJ7o8MteBkeA7rEOqEAJS30FYpP/hxhred8KSEdFUPYJNZz1kEo+QpJgRMIpAAq/STteuWJ56I0KI8ktE=,iv:z5SCMZ1KEHYkMcDS7+TMEZr928WcOKiOKYGElCJPv5k=,tag:hMjJXpCAl3LiFlWu1NzWbg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
