apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onlyoffice
  namespace: argocd
spec:
  project: cloud
  source:
    repoURL: https://github.com/enrico-laboratory/homelabV2
    path: k8s/cloud/onlyoffice
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
