apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-pvc
  namespace: mediaserver
  labels:
    recurring-job.longhorn.io/snapshot-every-day: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi