apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: transmission-secrets-sops
    namespace: mediaserver
spec:
    secretTemplates:
        - name: transmission-secrets
          labels:
            app: transmission
          stringData:
            user: ENC[AES256_GCM,data:0KMlQhU=,iv:XoKxfHf4Ty9UqlpZ2K7mDk+KHXxPgdM+Qu7QV6OsUIw=,tag:i37umCX4ZF7ONp0Dtfs2sg==,type:str]
            pass: ENC[AES256_GCM,data:oUYStII9pIk=,iv:yZmxXOYIJ8HCd/lNx7xvndst5WEYZ5b1kozCqSpmeNU=,tag:yM6Cq10Pdr/9AKJewYB4JQ==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWHJWcGNib1JEZFE3Wm5l
            R2pibnJPVUMwdE5Ta0FpNis1ODVXUmZKeVV3ClZCZFBEU09ndnhYVmFWcmZISXYz
            Z2o2Q3psVnRESytaZGNLdjdWS2JvZDgKLS0tIDlDK0RqTDdBMktkRjNSblFOYStk
            NDV5MGIrYjRQVU9JbEd6ZDZKQWZhZlUKD9WmtsY0iYkE9/i/Aw4C/sr3CT4zo8Dw
            t9IEOGL1HPq8T78Z94b21KpFzEJqn8xIVKGm01vl2uMzWTHEh5pL5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T16:49:51Z"
    mac: ENC[AES256_GCM,data:ZIW4rLc+fOvS0q5HWKPjRqWGK52A7YsysZMeFRcwzOV8DAqZLXYFDm0/8j7CsGbO/9WIEGuc/W0cE3Ikcy5wosefVI8X9Fmh9gMgV0/7WGIaTnolBIvyIUc7rSPtRyjXTI0ySvY7bjphcYLTVXqTP83YJ/fAoExAkesc+Y9zQv4=,iv:YSJHpRxpCQu2oxLcUbpsCEEI2P5yinQ8nZqXJFsF/sA=,tag:vVoSW2D6ieNyxiXh6l5cEA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
