apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflared-secrets-sops
    namespace: cloudflare
spec:
    secretTemplates:
        - name: cloudflared-credentials
          stringData:
            tunnel-token: ENC[AES256_GCM,data:A3c9OKJCTeEZ//JK8DCHHVnw4sMnBvzW70NvfITFIA2GtHgmxYVOAqADuxmx65iQo2e+eyvLtCfeF0nJmnH+HrgFYawramuiV6dLRrfqu8fKuB9jcv+3MEqOAeEbnHEOz8XQ3i/KPbdVDhr3EiD1eO/h5IG7kLoxlcN4tpj0tSLOs07cQsihsgw5+ZuB7wx6/x60eq7wfb2zBxO894TyakP2BjBzUUWpFQrMqIMkHl/ROKaoSZdq8A==,iv:DJrODL9RmzB8PNzqTzDq4JTrAO40Sf5PhkLByTDtpU4=,tag:l8PrAjCxmJI8HU8R6xqmWw==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NGNSTXZuNFFhU29GU0hi
            RTRQd0pJMDJQRENtVSt2Z0REWUJBM0x4U0RBCi9qdTYwSlpjQy9TZHYwamgxOUJ4
            bGxtelgwNzZZTXNrenBDVGNXVlErZlUKLS0tIEtHVWNQdXZvSzFCYkJQRG83bld4
            N3grRmZqQW80Zmk4cExjMnpMTU9TY1UKlDGEDiwrRzvuUkJcKLUsj2NZfEtoBvs2
            /ZvhLpnMDJz/yrnatNM+5QLj8+6unmJvsv6WAbFqBgt6JSXFlX+zIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T17:12:53Z"
    mac: ENC[AES256_GCM,data:UPNM17WKkw1/EuxkzLCXDJNxxTal4rf/sdAeA/BZrkiWXZygEGvHDHEkEG7yDatNevbc2KNrailq7vusLLSAfZbgsjfpMhNECj6Imb8bFEQn6FZSxn5Dzfx2e3kvlnB1YC5YlY6uLT7pvxfPYitDVCzrzgKUd5JVaGH5hSo5+iM=,iv:Ci3Y5HiNd/1HdwoWZzwUI4s7Za7wtRJkUbuDBNwB9RM=,tag:KTXdCdOGPR/+tW30+VNfUg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
