expose:
  type: ingress
  tls:
    enabled: true
    secretName: harbor-tls
  ingress:
    hosts:
      core: harbor.enricoruggieri.com
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare

externalURL: https://harbor.enricoruggieri.com

harborAdminPassword: "Harbor12345"

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: standard
      accessMode: ReadWriteOnce
      size: 5Gi
    database:
      storageClass: standard
      accessMode: ReadWriteOnce
      size: 2Gi
    jobservice:
      storageClass: standard
      accessMode: ReadWriteOnce
      size: 1Gi
    redis:
      storageClass: standard
      accessMode: ReadWriteOnce
      size: 1Gi

database:
  type: internal

redis:
  type: internal

trivy:
  enabled: false

notary:
  enabled: false

chartmuseum:
  enabled: false

metrics:
  enabled: false

nginx:
  enabled: true

portal:
  replicas: 1

core:
  replicas: 1

jobservice:
  replicas: 1

registry:
  replicas: 1
