apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-core-minimal
  namespace: argocd
spec:
  project: tooling
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.13.2  # Set the version you want
    helm:
      valueFiles:
        - ../tooling/harbor/value.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
