apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "sealed-secrets"
  namespace: argocd
spec:
  project: "tooling"
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.16.2
  destination:
    server: https://kubernetes.default.svc
    namespace: "tooling"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
