- name: Ensure Prometheus output directory exists locally
  delegate_to: localhost
  file:
    path: "{{ prometheus_compose_folder }}/{{ prometheus_config_folder }}"
    state: directory

- name: Generate Prometheus configuration
  delegate_to: localhost
  template:
    src: "{{ prometheus_config_file }}.j2"
    dest: "{{ prometheus_compose_folder }}/{{ prometheus_config_folder }}/{{ prometheus_config_file }}"

- name: Generate docker copmose
  delegate_to: localhost
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ prometheus_compose_folder }}/docker-compose.yml.j2"


- name: Bring up Prometheus and Grafana with Docker Compose
  delegate_to: localhost
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_compose_folder }}/"
    state: "{{ prometheus_state | default('present') }}"
