apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-ui-pvc
  namespace: registry-ui
  labels:
    recurring-job-group.longhorn.io/every-week: enabled
    recurring-job.longhorn.io/source: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi