apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "ingress-nginx"
  namespace: argocd
spec:
  project: "ingress-nginx"
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    helm:
      releaseName: ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: "ingress-nginx"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
