apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onlyoffice-pvc
  namespace: cloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-zfs-nvme
  resources:
    requests:
      storage: 5Gi
