apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: onlyoffice-secrets-sops
    namespace: cloud
spec:
    secretTemplates:
        - name: onlyoffice-credentials
          stringData:
            jwt-secret: ENC[AES256_GCM,data:j6uBcQiRE7VmVnRNngczyZNLLA/f/A+WyWUgJe2+A7wTzQLZ1Nz0V2NuIZA=,iv:hWNLgwym24tr8tawKdZADiNTPeaaPvf4ov5JWeEnZEg=,tag:20i8T0oB2PKozNIWXpsU2w==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbXhMdUtMVE9oNlkraFJ2
            WUx4djFSZHBiaTdHMEtWSVhSUm9RMkwyVUI0ClhhWUxhZGpyMVZqenRSY1RoMitx
            QVVVbGFsZndrQ0JMbnNpN1VvZjZ1NDgKLS0tIFUyZS9INjd1cTdza0ZPa2dMSzlk
            NzlHR3pyOWpZdzdtTk5SWG9SNm1kaEUKpepPA+ol6kqrXf9LmOuqoEegz2gM6isg
            XyQH1Qp/CYBKc+W6qjZYti0/bWtPeB8+lDA2piGupkd2t9HidvZwiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T15:26:51Z"
    mac: ENC[AES256_GCM,data:rEoWqtPOoZZ0ATtMRIujD3JhK9P00rEkl5v0mtJmXV0gVTDqdQw5tSLkSDoWWM+rCHrqqkLvM5XOm3hT97ebTWLyvhVaXrKv/xQjxL2muJ7UuWIeHZ49c91MysoHZcxqzmmUtQliBC9L8giQv+X1Eo1U0HxKsL5PflHqBgAvd1A=,iv:8ukWHUKCK62J36xbokC2CL6TkN4hnI24aTt+9x9GPnw=,tag:EzFqP67HhlScxWSqY+ZKSw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
