kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-gpu
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "480"
  fsType: "ext4"
  nodeSelector: "gpu"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-sonoff
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "480"
  fsType: "ext4"
  nodeSelector: "sonoff"
