apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: karakeep-secrets-sops
    namespace: mediaserver
spec:
    secretTemplates:
        - name: karakeep-secrets
          labels:
            app: karakeep
          stringData:
            MEILI_MASTER_KEY: ENC[AES256_GCM,data:acBv3WOh2cnSkQ8a1p8f+xAO,iv:2XekTgaNU8p4RyhIGMXtGQL16jVOKYtPkgNVA/IMevM=,tag:NiLOOlO1GL2cU0hRVbCN3g==,type:str]
            NEXTAUTH_SECRET: ENC[AES256_GCM,data:fF6q6XSAzuWwwWZKUKojDibl,iv:DZjS47+cLeTS4yN/yNJEPRZDjJY/FKgZN3tr+8C9U6k=,tag:uknuib+wzqyQmM+v9Y/WfA==,type:str]
            OPENAI_API_KEY: ENC[AES256_GCM,data:v8I4HKoTHVIDHkoqdCfvYudZgA==,iv:AL/nQ4O4glQp+lrWHfTDuzxJqBTPchZU4Jcq8sJrXU0=,tag:4KJ5C/SzKSCev/I/3VLU5g==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dElKSmt2Q0svUDJ6cnJx
            Vmx2eXNmWHhCcWRKU3NWQTRodjhJQUNyUndvClhkT0IxRWU5M0UyMVkvN3l4a3V2
            UFkrZ002RW5aYXhsVWhJVU9KN3pRSkUKLS0tIGxZNkVsZ3VzVjh3Y2poZHFnaVFs
            UGhCK1pWcmt3bkdoNEF5K1pyL3BzR2sK7XMffeaMcVq6/esHL7uuUdKk0BDxmvDS
            +bUoNovBy9xhtG3enU2q9ST7/neGS+vNUw/sybWuyz1t8vJo7zQYnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T16:49:51Z"
    mac: ENC[AES256_GCM,data:klHb4c18FWpBHXlBMtExZmh99tSmnRiOkUrA/HBdhnN3msyhleD4d2ZifBd0oc84brGoF+WQ2ykn1aMAgfx016vlJzcX1LtCP0llphxpuD4JihTvgscki79yf6zkjEOxKVnAjJiS1QMijZUZqttbNPoenNTfnShdYNhphDx4pds=,iv:rJvD3Jpc0EZNyIJS5VTqjDXnyFk7GVME801ZzxvV4mw=,tag:oMfN8wVNOwyl8teGnKZxHA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
