apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui
  namespace: ai
spec:
  replicas: 0
  selector:
    matchLabels:
      app: comfyui
  template:
    metadata:
      labels:
        app: comfyui
    spec:
      runtimeClassName: nvidia
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: comfyui
          image: yanwk/comfyui-boot:cu128-slim-20260518
          ports:
            - containerPort: 8188
          env:
            - name: HF_HOME
              value: /root/.cache/huggingface
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: comfyui-data
              mountPath: /root/ComfyUI
            - name: comfyui-output
              mountPath: /root/ComfyUI/output
            - name: comfyui-hf-cache
              mountPath: /root/.cache/huggingface
      volumes:
        - name: comfyui-data
          persistentVolumeClaim:
            claimName: comfyui-pvc
        - name: comfyui-output
          nfs:
            server: nas.enricoruggieri.com
            path: /tank-data/comfyui-output
        - name: comfyui-hf-cache
          persistentVolumeClaim:
            claimName: comfyui-hf-cache-pvc
