apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui
  namespace: ai
spec:
  replicas: 0
  selector:
    matchLabels:
      app: comfyui
  template:
    metadata:
      labels:
        app: comfyui
    spec:
      runtimeClassName: nvidia
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: comfyui
          image: yanwk/comfyui-boot:cu124-slim
          ports:
            - containerPort: 8188
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: comfyui-data
              mountPath: /home/user/ComfyUI
      volumes:
        - name: comfyui-data
          persistentVolumeClaim:
            claimName: comfyui-pvc
