- name: Install NFS
  ansible.builtin.apt:
    name:
      - qemu-guest-agent
    state: present
    update_cache: true

- name: Start qemu-guest-agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: started
