apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
  namespace: mediaserver
  annotations:
   cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: nginx
  rules:
    - host: "jackett.enricoruggieri.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jackett-service
                port:
                  number: 9117
  tls:
  - hosts:
    - jackett.enricoruggieri.com
    secretName: jackett-cert-tls