apiVersion: v1
kind: Service
metadata:
  name: organizr-service
  namespace: mediaserver
spec:
  type: NodePort
  selector:
    app: organizr
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
