apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant-secrets
  namespace: argocd
spec:
  project: ai

  source:
    repoURL: "https://github.com/enrico-laboratory/homelabV2"
    targetRevision: HEAD
    path: k8s/ai/qdrant

  destination:
    server: https://kubernetes.default.svc
    namespace: ai

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
