- name: Configure DNS
  hosts: dns
  become: true
  vars:


    docker_gpg_keyring: "/etc/apt/keyrings/docker.asc"
    docker_gpg_key_url: "{{ docker_repo_url }}/gpg"
    docker_repo_url: "https://download.docker.com/linux/ubuntu"
  tasks:

    - name: Network configuration
      vars:
        nameservers:
          - "{{ inventory_hostname }}"
          - 8.8.8.8
      ansible.builtin.include_role:
        name: network_interface

    - name: Install qemu agent
      ansible.builtin.include_role:
        name: install_qemu_agent

    - name: Install ansible
      ansible.builtin.include_role:
        name: ansible_install

    - name: Copy ssh keys
      ansible.builtin.include_role:
        name: ssh_key_copy

    - name: Install sops and age
      ansible.builtin.include_role:
        name: sops_age_install

    - name: Clone homelabV2 repo
      ansible.builtin.include_role:
        name: git_clone

    - name: Install node exporter
      ansible.builtin.include_role:
        name: prometheus.prometheus.node_exporter
