- name: Create dns vcm
  hosts: pve-node1
  become: true
  vars:
    cloud_init_img: 'jammy-server-cloudimg-amd64.img'
    image_url: 'https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img'
    drive_format: qcow2
    disk_extra_size: "29748" # 32G in total
    gateway: "192.168.100.1"
    net0: "virtio,bridge=vmbr0"
    vms:
      - vmid: 149
        state: "present"
        disk_type: "scsi0"
        vm_name: "dns"
        template: false
        onboot: true
        cores: 1
        memory: 2048
        nameservers:
          - "8.8.8.8"
          - "8.8.4.4"
        searchdomains:
          - enricoruggieri.com
  roles:
    - pve_manage_vms
