- name: Create K3S vms
  hosts: pve_node1
  become: true
  vars:
    cloud_init_img: 'jammy-server-cloudimg-amd64.img'
    image_url: 'https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img'
    drive_format: raw
    name_suffix: "k3s-"
    disk_extra_size: "29748" # 32G in total
    gateway: "192.168.100.1"
    net0: "virtio,bridge=vmbr0"
    vms:
      - vmid: 121
        state: "present"
        disk_type: "scsi0"
        vm_name: "{{ name_suffix }}121"
        node_name: "pve-node1"
        template: false
        onboot: true
        cores: 4
        memory: 3092
        started: true
        nameservers:
          - "192.168.100.80"
          - "8.8.8.8"
        searchdomains:
          - enricoruggieri.com
      - vmid: 122
        state: "present"
        disk_type: "scsi0"
        vm_name: "{{ name_suffix }}122"
        node_name: "pve-node1"
        template: false
        onboot: true
        cores: 4
        memory: 3092
        started: true
        nameservers:
          - "192.168.100.80"
          - "8.8.8.8"
        searchdomains:
          - enricoruggieri.com
      - vmid: 123
        state: "present"
        disk_type: "scsi0"
        vm_name: "{{ name_suffix }}123"
        node_name: "pve-node2"
        template: false
        onboot: true
        cores: 4
        memory: 3092
        started: true
        nameservers:
          - "192.168.100.80"
          - "8.8.8.8"
        searchdomains:
          - enricoruggieri.com
      - vmid: 131
        state: "present"
        disk_type: "scsi0"
        vm_name: "{{ name_suffix }}131"
        node_name: "pve-node1"
        template: false
        onboot: true
        cores: 3
        memory: 3092
        started: true
        usb_device: "host=1a76:55d4"
        nameservers:
          - "192.168.100.80"
          - "8.8.8.8"
        searchdomains:
          - enricoruggieri.com
        disks:
          - disk: scsi1
            format: raw
            size: 20
            state: "present"
      - vmid: 132
        state: "present"
        disk_type: "scsi0"
        vm_name: "{{ name_suffix }}132"
        node_name: "pve-node1"
        template: false
        onboot: true
        cores: 3
        memory: 3092
        started: true
        nameservers:
          - "192.168.100.80"
          - "8.8.8.8"
        searchdomains:
          - enricoruggieri.com
        disks:
          - disk: scsi1
            format: raw
            size: 20
            state: "present"
      - vmid: 133
        state: "present"
        disk_type: "scsi0"
        vm_name: "{{ name_suffix }}133"
        node_name: "pve-node2"
        template: false
        onboot: true
        cores: 5
        memory: 4096
        started: true
        nameservers:
          - "192.168.100.80"
          - "8.8.8.8"
        searchdomains:
          - enricoruggieri.com
        disks:
          - disk: scsi1
            format: raw
            size: 20
            state: "present"
      - vmid: 134
        image_url: 'https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img'
        cloud_init_img: 'noble-server-cloudimg-amd64.img'
        state: "present"
        disk_type: "scsi0"
        vm_name: "{{ name_suffix }}134"
        node_name: "pve-node1"
        template: false
        onboot: true
        cores: 3
        memory: 3092
        started: true
        nameservers:
          - "192.168.100.80"
          - "8.8.8.8"
        searchdomains:
          - enricoruggieri.com
        disks:
          - disk: scsi1
            format: raw
            size: 20
            state: "present"
      - vmid: 140
        state: "present"
        disk_type: "scsi0"
        vm_name: "{{ name_suffix }}proxy"
        node_name: "pve-node1"
        template: false
        onboot: true
        cores: 2
        memory: 2048
        started: true
        nameservers:
          - "192.168.100.80"
          - "8.8.8.8"
        searchdomains:
          - enricoruggieri.com
      - vmid: 149
        state: "present"
        disk_type: "scsi0"
        vm_name: "dns"
        node_name: "pve-node1"
        template: false
        onboot: true
        cores: 1
        memory: 2048
        started: true
        nameservers:
          - "8.8.8.8"
          - "8.8.4.4"
        searchdomains:
          - enricoruggieri.com
  roles:
    - pve_manage_vms
