apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nextcloud-secrets-sops
    namespace: cloud
spec:
    secretTemplates:
        - name: nextcloud-admin-credentials
          stringData:
            nextcloud-username: ENC[AES256_GCM,data:FZG2IG0=,iv:zX3ZplkIwyIVBGPpi31BItugf8e8M12P3a6kOnC0Zik=,tag:inYV5cTaXPvkZmqnfbiw6g==,type:str]
            nextcloud-password: ENC[AES256_GCM,data:JJ9Y+Qbjz8vW0FpgNUrV5eakvNf5GhH8/w==,iv:P8PkdZaNanBS2GShcA0VHL/3K7+LK1ow8jinRsaHK1k=,tag:+2VNtRFtd6dfAe2WJGgwNA==,type:str]
        - name: nextcloud-postgres-credentials
          stringData:
            postgres-password: ENC[AES256_GCM,data:So1/i0Hz/Zk+1E4G5YjlfWXVSOssOqlyEg==,iv:HppzkpW7j2XWOwte7ucnSX0W8UHbqTw4zoAuGA7M9aE=,tag:k7iU1T2nHMsKoJ36ScAtNw==,type:str]
            password: ENC[AES256_GCM,data:3vdqjJMhWpBoMJkJVz4xuv49Wp7TUQyO9w==,iv:4rMSPsiy7VV6lmCCSUAWKHnGY5rrev7T4SX9v8YL5uU=,tag:iNMWcPfNzxrUwdFvhTuYeg==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQU2lNZE40a21sMDBGVVlz
            UFg3c3FXbk5FNyt1V2VDSG9oQ2RnVk1GekJvCmN5QzlmUmhKSkMzUlIwYkszb2th
            amNoNjVYbHFOdGxmUzVwZ1U4UUlFUTAKLS0tIDF1ejJKdWlaQ21oNllTYjI4MzFV
            VElOeWcvR2xJYlFzL0ExeUNFU1ErTW8K7mDuL1rPgPw7tJIo8QyHga68ufEb4gys
            fXCG2LQNCIIn7fLet05Mrz7NWVodO2+D6hnVNC4vuMuFe/VUHdlJoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T18:47:29Z"
    mac: ENC[AES256_GCM,data:W793vuxTEqnn7rVUUEhPm18t2nyY9Do4Bk0AmsGbm96SotFYjTgNnt62EK+skZ+eOttP0qa/K1uSgmN73uuhTOrvDenIucetsXABWoFn9lGBD9TVWhfWyUy/k0D5NQEnsrUOU2XxwfaZcGLSUWox2B7fZfa5W9+A/rsF6JMsi1E=,iv:YWFuFIV03PmP/mgPNatYsNq6Z2rL7AX8dge/kRpn/ps=,tag:zZ3q8bvJyZBEyTPV6NEmeg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
