apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nextcloud-secrets-sops
    namespace: cloud
spec:
    secretTemplates:
        - name: nextcloud-admin-credentials
          stringData:
            nextcloud-username: ENC[AES256_GCM,data:Z+iBqIk=,iv:pGDI3NtFaO5pn/DfhRWI1le50KJ4E7yOw8/BbAG9h9Q=,tag:by9sncZbS81dG7pNg3BOvQ==,type:str]
            nextcloud-password: ENC[AES256_GCM,data:8ucV5vBaQDKZZWzdSXCNM8EbU6HwaBfe8A==,iv:LneSwPqNxrkae+wzl6FQhAgVVOKUfldCiyf12yw6vOE=,tag:7Dibdwf0VXTltPLfxXqZQQ==,type:str]
        - name: nextcloud-postgres-credentials
          stringData:
            db-username: ENC[AES256_GCM,data:9VsEVAow4Qmq,iv:HlNDoQ8QHNvp12vVaP1pgDyKHpIYCV5ZkVECEKnHjXE=,tag:FA3MdsQO5jum+K+Lr9buPQ==,type:str]
            postgres-password: ENC[AES256_GCM,data:xWzkmorUKmAOGZopnF6HWkhktt7SqeiviA==,iv:6U2FyJexAvklIF4geXPs1FOCKHuEbZpRsNy+ukqJUXE=,tag:tuMXRP94vc9ekfmda0UgKg==,type:str]
            password: ENC[AES256_GCM,data:Yw+//XIUf5rhxJB92+EkH+k6p9Uv1ejlLQ==,iv:Z66uFcO8GUegAdNXHHMABhsLVJa1zeyKQCX5ZMLYGwE=,tag:jqUzjHFzLXkjxnEVYge17A==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y1FCK0N5WjNMOGoyQTNZ
            V3FtVVBxRTlVeXhtQTVCS1BsOVd2Z0UwY3lVCkVTRTA5ODV2VTNTOVNFVTl4R25t
            U1RQM3JrK2l1WVdrbFdObHUydjI2NUEKLS0tIDJsVHduQmpGMkU5U2RvcHBkSVBJ
            Q3NvVENPTDRvSlEvNWs3N0FVQ0FKbjAKNKafiY2gf7dlu0LQVS+LjCFwD9bxG4jS
            OOytXLnXYG0+w8f+sNiFcvsjdbaZxQUxmeswDH07502sbZHLNpAOyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T18:15:34Z"
    mac: ENC[AES256_GCM,data:HAD3n/SbLH2I9odue9ldg+t/JyboR9j/nRjTRZQTml/Wd5JH82cUY9sbyRFXwITG30ljzS8rnN/ATV9mmqKg4Y2B2grAgE+Hdm3Jfyp3ZHGs+2n1JAS6io4/rkRoLCUau2PwOLNnUEo6xGfeRnwVqWv1M1DG3/HPM08ck7nX1DA=,iv:IjXIt9bh8albwkgC4qrTmTPx49SfzpBOQCa05rhJUnM=,tag:BUWrDPSmlRjsARVx86eV4Q==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
