apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-automation
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      nodeName:
        k3s-134
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:1.40.1
          env:
            - name: TZ
              value: Europe/Amsterdam
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /dev/ttyACM0
              name: sonoff
            - mountPath: /app/data
              name: data
          securityContext:
            privileged: true
      volumes:
        - name: sonoff
          hostPath:
            path: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20240105134827-if00
        - name: data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data 
