apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-automation
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      nodeName:
        k3s-2
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:1.40.1
          env:
            - name: TZ
              value: Europe/Amsterdam
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /dev/ttyACM0
              name: sonoff
            - mountPath: /app/data
              name: data
      #            - mountPath: /config/configuration.yaml
      #              subPath: configuration.yaml
      #              name: configmap-file-india
      #            - mountPath: /config/automations.yaml
      #              subPath: automations.yaml
      #              name: configmap-file-india
      #            - mountPath: /dev/ttyUSB1
      #              name: zigbee
          securityContext:
            privileged: true
      hostNetwork: true
      volumes:
        - name: sonoff
          hostPath:
            path: /dev/ttyACM0
        - name: data
          nfs:
            server: 192.168.100.61
            path: /mnt/fast-pool1/home-assistant/zigbee2mqtt/
#        - name: configmap-file-india
#          configMap:
#            name: ha-india-configmap
#        - name: zigbee
#          hostPath:
#            path: /dev/ttyACM0
