apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  namespace: home-automation
  labels:
    recurring-job-group.longhorn.io/every-week: enabled
    recurring-job.longhorn.io/source: enabled 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-sonoff
  resources:
    requests:
      storage: 50Mi