apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: home-automation
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.241
spec:
  type: LoadBalancer
  selector:
    app: zigbee2mqtt
  ports:
    - port: 8080
