apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: navidrome-secrets-sops
    namespace: mediaserver
spec:
    secretTemplates:
        - name: navidrome-secrets
          labels:
            app: navidrome
          stringData:
            lastFmApiKey: ENC[AES256_GCM,data:61y0fBBmZLZNS7dc7n05y5gborIi4Co/pQYXOkq8Bh4=,iv:eV2zqRQzXxqRAFx1j1RvhooaGdWSmI5sBWxTO+7cPnE=,tag:CKjlf9gZGSBXYiegPInhmQ==,type:str]
            lastFmApiSecret: ENC[AES256_GCM,data:VsZ/Vjjh0Pzf55kItxHs746wIbBwaC5tT78AIExEw5I=,iv:YUR8tkkWAM0f053s9zWpHXYxP0rP7cGla11MrAG23y8=,tag:oT2uk8PnZfc5cWU8lvYYag==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK1lhQzBlYmZDMkZIYVFo
            aVFVUTlyY3AvZWNYL0NWek5lYWZrTVYvNHhVClVMSTJ5QkJvNlVZMmsyRzlqV1px
            aERUZkhKZzUzZDNFa2kvZERwenlKSEUKLS0tIE1sVXlic21DcWoxcDRGTzhiYThC
            eW5KanBHWkMxR21nZXRKdTlkVUlkckkKgpXl7uOR1xwRij2vmJgbSYiRr71NCKoK
            FX/fI8A37pOSHn5WIU0BEe2J2UXMkz0EhDYb6RvZa+G/wciOLsd3sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T16:49:51Z"
    mac: ENC[AES256_GCM,data:P7iDxLzfS3amhdRtJI1hZys9biMsgAFRB5tut1ZXyDfhGi6pVwRdLxpZvLtf6dmNAbUFJJ1HAryE3bdQTQx1b7iEIAhS+ctNy+kwDQRU3JzB0tt8ffs29e5CSrJhejZ6qjJ0dQ0WN+1sCf+hCuB8KkS2wzUZFkVmC98n9RJ7xes=,iv:it7ziYmj6FhxIk4j3/v5HoMhvNLS3eeLpE//g9OJucY=,tag:hs/Er6VkIEdyUpyp1JJvRA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
