apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: prometheus-secrets-sops
    namespace: tooling
spec:
    secretTemplates:
        - name: telegram-bot-token-secret
          labels:
            app: prometheus
          stringData:
            token: ENC[AES256_GCM,data:Kt3bzbr7x38YQJHGrjiWpI88CoZZSAphiw3V54+yhk12g4SGumapBClljNFayQ==,iv:tJLNszhgZ1zzHSHnhfACJ0lTD0LNWLWRLhNo32bJzfg=,tag:vkFWL2VzxwDl5wCkj+WvrQ==,type:str]
        - name: prometheus-grafana-admin-credentials
          labels:
            app: prometheus
          stringData:
            admin-user: ENC[AES256_GCM,data:SaJ5eSc=,iv:PM2v2CJeaHMkmhjmv80GdfuDjaOZCOANzWfrpmYXFDQ=,tag:3kXMxKLO4GEjdE+z/7Gqaw==,type:str]
            admin-password: ENC[AES256_GCM,data:ffTXCP1Pxu6KFSo=,iv:gC7j8z8GStDykoxxn66P39cMCOK6AjTbpuJHIT2VQxU=,tag:Je0jP1TQ7BW8u8YGzUJtZQ==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VDQwZTQxNWJvTjV4ayt5
            bXN6S01JY29zeDQwOTJlaUhvWmZPc3ZsbjIwCk1vWUUxZmpTVUs5U2pBUXlRcEQ5
            Y0cxN0xyZmhmNWdZcUNVZFh1ck1YdGcKLS0tIFAxdGhqcHBPcXlVd3B6NUJMYjlO
            aG9jTDNyeC9TcWQyUlE4N21JZWJ0aWsKpgGRKWdLsz95iKdhgsFF+cVq/pfGTqTQ
            BhcVmi8Bkb0QFCxQFXxCbwSwaxm08BPyvtYnGJuPtLs8i6fEwTKV7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T16:49:51Z"
    mac: ENC[AES256_GCM,data:BPNOK0WWV7LUyJKbyHHxbiLmnHPPjhD7TyN1bZ9ecUl3CwiJQ8OvdUvgQ0EE27G17A7BHXcOduVCC09ymIRkOMxcqGVuyDG6RqtJshgCAXvRNEvAfHNhbHiHl/gqu/2ghbSa2uxb1mDSUPTo5eVMkQeqA12ep+QvoQ77iz5ODic=,iv:dC68jgpI0JJFK00KK1DltHAzEWrWTNZaqpUh0zyuAss=,tag:/nvgHn24QeVs1AF+dR+1Yw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
