apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: mediaserver
spec:
#  tls:
#    - hosts:
#       - "jellyfin.enricoruggieri.com"
#      secretName: dns-cert-enricoruggiericom-jellyfin
  rules:
    - host: "jellyfin.enricoruggieri.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jellyfin-service
                port:
                  number: 8096
