apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto
          ports:
            - containerPort: 1883
            - containerPort: 9001
          volumeMounts:
            - mountPath: /mosquitto/config/mosquitto.conf
              name: config
              subPath: mosquitto.conf
            - mountPath: /mosquitto/config/user
              name: config
              subPath: user
#            - mountPath: /mosquitto/data
#              name: data
            - mountPath: /mosquitto/log
              name: log
            - mountPath: /mosquitto/log-temp
              name: log-temp
            - mountPath: /mosquitto/data-temp
              name: data-temp
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: log-temp
          persistentVolumeClaim:
            claimName: mosquitto-pvc-log
        - name: data-temp
          persistentVolumeClaim:
            claimName: mosquitto-pvc-data
        - name: data
          nfs:
            server: 192.168.100.61
            path: /mnt/fast-pool1/home-assistant/mosquitto/data
        - name: log
          nfs:
            server: 192.168.100.61
            path: /mnt/fast-pool1/home-assistant/mosquitto/log