apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc-log
  namespace: home-automation
  labels:
    recurring-job-group.longhorn.io/every-week: enabled
    recurring-job.longhorn.io/source: enabled 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc-data
  namespace: home-automation
  labels:
    recurring-job-group.longhorn.io/every-week: enabled
    recurring-job.longhorn.io/source: enabled 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi
