- name: Install prerequisites
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

- name: Install pip packages
  become: true
  pip:
    name: "{{ item }}"
    executable: pip3
  loop:
    - ansible
    - docker
    - docker-compose

- name: Copy collection requirements file
  become: false
  copy:
    src: requirements.yml
    dest: /tmp/requirements.yml

- name: Install Ansible collections from requirements.yml
  become: true
  ansible.builtin.command:
    cmd: ansible-galaxy install -r /tmp/requirements.yml
  args:
    chdir: /tmp
  register: out

- debug:
    msg: "{{ out }}"

- name: Delete temporary collection requirements file
  become: false
  file:
    path: /tmp/requirements.yml
    state: absent
