apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: qdrant-api-key-sops
    namespace: ai
spec:
    secretTemplates:
        - name: qdrant-api-key-secret
          stringData:
            api-key: ENC[AES256_GCM,data:8pMYL0i3gH7VTW5uSFbH3oRo9c83M8bOc1JdhzwG01I=,iv:LMaNF4n9AsQfU1AJ0hmkw0OLnyoc0OGVVOpxw1WsFfg=,tag:vPUR3zpdxCYaJhXTdRHIQQ==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdTlyTEorNlRIb3JMTkRL
            cXgzc0cxRS92c3g0MUF0MzQyeVVBbEpqV3dZCkwwOTFObmVhU0kwTEx5WHFtcGhj
            Q0s5YktRU0NUbkdudFBYQmVlRWZMazgKLS0tIDhNc2MvZ004QnRucFhQd1ZuVjFL
            dWM0bjV2MzY1K1BlZStyc0ZxQ1FtR0UKMRC1M1a5LotfC56UgzG3BoZ8CxDM6EMY
            r5+zXbbkbO6ydmhedyevHxYzIBVWGCQpN398unLSE3AsNkDKO9IWmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T20:22:27Z"
    mac: ENC[AES256_GCM,data:Tlk+RaFloPg5jLvDEmEdYBMYUTiaJoBKdUY7PmNVcbH1kOl9emqp8MiU4km9uJlzXhE6XNOMJuLhT5e3h89gYDnOIWkno8k+sAfvA4JTo0DXJaGtlAWCAKN2Og+eMP5m491Ea/Ym9VsCUIxbIX4a/z3tDACKLPoTS/swpjbFIw8=,iv:OOdWAG2mB8qyxpvtBhC9Iubny7cX6GiuEdXBZXYiBG8=,tag:kMoXKRe+EJWyeZJ4YL6Rfw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
