telegram_chat_id: ENC[AES256_GCM,data:QchQ1Vo9kcb4ig==,iv:Xs472itdQXJSNJ8kfhdEMWzKBqP9+ConInXE4JYr4Dw=,tag:g2ovWpYtKPOX9F+67Nz/JA==,type:str]
telegram_bot_token: ENC[AES256_GCM,data:EyUv6kCPHg+Dvu1voiWI6JJRAwkOTtT0S9tfCq5mP5KYdGDDqfaBO7DdGf9sag==,iv:S2S8ZehbXwxDiFFLy9ywUWDoQdwSSAAEHDGkE/8xdvk=,tag:aB7ZcZZPuLbns8oXxtlS4A==,type:str]
main_user: ENC[AES256_GCM,data:tq79OMZdQzkc,iv:mlVAMDvy4vks5zrKCxY/UbL3UQRvd3fRrBy63WOtegM=,tag:EROqJMDgCJp4GRDcvAtslw==,type:str]
search_domain: ENC[AES256_GCM,data:e+dqQdxitK9AjAGQS/IxVLIt,iv:XsFW2D8JzQmSmgh+RpMv+0AUKJ+VlKD7nzY0SsQPLrE=,tag:zYpXBO6NUXEWj8ZS76Y43w==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZHhiQko3Z01aSXpxNlAv
            RXRaQ054MEROQVZhNnNUeFZMRTB0RU9yK1ZvCnVsMDQ1UGZmWHd4aEFUY1NsN2ti
            N2ZmSVJ1d2ltdldNeFQrMXlkUDZoRW8KLS0tIHg2Wm91dXVuazUxYmJMOVFGTUQ4
            dUJCMkhmRUlQUUZyMXpiWU03WXh0aVUKLVCuTkqlLBfOg5xApPqxsrhjKbBt3Wrz
            s/JkrADPPo20xBMuHoThGYR0w3z/1iijxMAFiHiBxfytPr3pssYDaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-03T08:27:53Z"
    mac: ENC[AES256_GCM,data:G/1ue7AsnUTvbBqG3L+POzBYQOPSGLQeQsJl1/Z/i4RLyZdRH14LTdAcQWBCL8r12xnni0J0XoSIxm5u8tgZFvzW8foIL1jmohhOinTEyoy2JTuAwZ5BK2y75Oa25FEGDSh2AtfzPtgDDZBDlJ6gOooibbIdxUPn5bKjSKjdmFw=,iv:EkYZmAblfzWf9zByf29JIQL7+AtkxvvZQMm6Jt14O2g=,tag:McBU4Bu5Qcgt4Yfe8mb0jQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
