---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgB2YBY55SQKVmTET0QSHI52n+pwkC2rjbnzytzeeIxo5VySAPITrKnKFFP/MWntk8ey9ePxzW9HoB+tbMeD9Kf0iLD6v4c3ia5Ql5a1vmdLhe/Wet5+BIilSfzyvveynYYjIrY7XBDxDqajYGRfCRghcauBoZseB3mwzv2uH45+sv1ABPVcNW5J2PapoBMYIqfm9saD7wUWo3TCW4nAh+ciCWqQlHPNl/E+louBmuYYaPXkeU0HM8Xpv+ciq/8yWB+/hLKZjIueWYNC6SWvBzUXaDInOTxvYH8fo/Po72LfoyuNrhbdeMfQyhTc8mnU2ZTep1rmjFbYHi6N55QlzcLORFSQh9DlQeGtPNtoFKnM9CNIrp41433hPCAZKXZYj2WFvtmmrMiyFMzNYQKYtbOAEpBbuEyfyitFqm0ay//7sQ4Vk0PU3bf+EBn2//LSNRs12vZgzqkBRCBbLXBuQucPtiVw5MZ1sWLnEYUSZGSWVuo6EgjpFGdzFijmVAiYLOym49uA+P6XinepVapH0FMyf5ZJFGoRZZFme887WXBYZYHTs8uXO1evvXemIBo8Sln/8ZIlizKRDqTfm1+H2SWN/cFB4/G5FG1R0CzCGPn5nKDWbNA/sKpgE1ZtjNd9jdh+Jsagy35+TUPxfwx4+KJlP4aUHPeUVJC7T92gZ+fWbYjPYCTqD43wPSsIltGm8Ik7Of2+/d6iag==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
      name: postgres-secrets
      namespace: mediaserver
    type: Opaque
