---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgC+1l6/qH/xclBosBP8F+zCUUVYSQbzNw81WbD0YTFvBUQDS8bVhHS90HI4OpXROZ/UQQninDLLtJllWcaR+ZpI5pvdUV6zDnA2ml9cdNnrF36qP2RUH9Nxihmg0RwyAvd6t0ev0+rAwch+IKyH4z1bpJ3t4gR9Vx4sXE1cImPv5z6/+EQZTZcIm5ASA/YGKoxYS4dOFkY0jnBdWq+Ski/9MDzz6Mv1a0RtAm2EanDLdoNoSXxSEmGCq4tgzVjGSmwAUMgaYboASQfriu5K2Hv1wiJpFunnNuVPKSV1B+3ibWFYlq9MBK4w5VJe+B874iMquNspJBomLARzAp1Av7yFKx3337dSETB1b/GCZvR0yuekuMIlfP0+5+mmpI/ptgAp3VKIlZ8kj/FBpob/qV3wR12wvch35iYRycAWgUH4LF6GvIi0ePZ3UZZOMd+sLRobGL46G2Y3CqcUnC5SCMJ1ZiG/TkLSMM6OUbBkmY1Vle6ENj8lCyxXh1QrUtQ72XtHwb5stWsQcgytI76qSapXTluqudKHsjXjrB3Z8qp+r2riL4LgPIss5pPVO25q5eSeUlzbkbDVzke9eCpfSTarKEoDJuOURto1K/7wRaMuSWRvalVbOWBFHmy4pIrIeJ603fXe6VYOraNKDOl/rlsfVBGpRPXSbbeoQ+UgiGF+47iVb2y0Yjcq/eIxbAX0O+eJQwVRN07m+w==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
      name: postgres-secrets
      namespace: mediaserver
    type: Opaque
