---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgBslSes1CgXXMFk+SB24Q2RPX9+vey8n7ecbblH0dAByOXkirCsBEr0wylB2Mg1xQdoe4Kx+dsZjM9STltGVuM3h5sRxem3z/odyfDvB/bz644Y0dSe0RT64gVKS7FOi0YsCqUPZAucheOtpxw7iA+XdFQF2iyWODEl+TCH3pwRiO44SuYF2fAwUP41NBHPiXuYs/rnHEKRrH56lVnrEQbKx/ObSDeIa5I10ZKUGBcKHqJss6RPvpjSi0Qd8o/YLFJHKym09WH939p8vgRG6mxPEYAqUF3VV3jVE7C0VKj0m/pfpPvH1J+D6hTZdilN+BohwmcQLTDOpX/RTib0GumWxtatztnhuan7RpwyM+HQdsOukx39OAf0VQocKb36JgHHmpX71XOmVK7aU9irQZMM627oN8smSTiCTn9kx/WOiGOlhoeNmuUUQUptz6UqQ9+RKtbsOy/ygy3MYq35iUrh9t+EkOXQNKFkun55azPF184V5Hs0aH9guz4WC7FCDYt7P3UunHEC3qCJDbK/cWCPhOwdY9xcx2HNDY5gZ6fyqVG+d95mWMQrqIycj9QtLpFmQ6TbWhBJtyTjfocHbebsMysYlWidUMB4Z7hzS9BDlc1L+AthYGVODynwibH51PSI6qbj5BD00ScZVj4dHT94s3Nay8X8ZBEHcCdPC838DcdAUGNEkYdnyez85gBHnfNIIlAm1992cw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
      name: postgres-secrets
      namespace: mediaserver
    type: Opaque
