---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgDG+7uQvFHPc9oyOz7/IJ8nQWJuNV6nwpG26zZ9DS6J15vAJJi7am9OadHIoe3B3lk5i2AIooY2OaeskeC/tQgyx7IntQ0QDkvZPxhRA2/u/+8pa24i0lz60gMD+1QD1xcXnGpkpUpwaa3P5ccos4HStfHdIpf8ZqRTdEfoXsE3xtjrZh3T5X6r1gueCOotkInCx0HkOTS17JpYr1UJT4aBfutQLH9e8VWltOcdSKya/LYjrXcz2IxPAT/+hLLKVimY94cAFtlxw5DOatQFL3czIZnAF7KWGuBB+uyqisIJMcUVzEwvRb1F/E8sGcx82b82HuPdZC+/qS4DdT0F5jtrRaLwF+Xj7gVKv1rCO6PQvkci79sOm0GvXnz43/JywmaaiSCpo+2juNgErWEfssfdGatFOUUmgzjGxZPDyqTg2YExZqHYVzWkodL3f0+ndZFFMqeGBKw/4RLAl93eGH4Xj06xzh9F0Br5q0V4ci8QQl4ObKfZrNaba/SWipkvVJOVvRrGrgWHU7s/+g7KpXbwfy4oESIw6gT6EVly47gfCI34IjdBvusYvyCynPsxbeUkD7OGk0vLMVrZ5Vp2hQmkUXP13xJ0DWEketgK8v9TNt5UDlLEYVtLFiTp1Suf+8KoXGX2/JmisHqJfpZ73tJkP7izu86JgJMnY/X+V4FHq3Xp/UrjsIo515kydEeDj0kT62ZyXUS8DooaaiB7qQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
      name: postgres-secrets
      namespace: mediaserver
    type: Opaque
