- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist
  register: upgrade_result

- name: Check if a reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: send a telegram if machine require reboot
  delegate_to: localhost
  become: false
  when: reboot_required.stat.exists
  uri:
    url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
    method: POST
    body_format: form-urlencoded
    body:
      chat_id: "{{ telegram_chat_id }}"
      text: "The host {{ inventory_hostname }} needs reboot"

