apiVersion: ENC[AES256_GCM,data:HEgflmKLT7vtPUFRWktjk1CPAHpDmcy75kq7,iv:zs07ym9BBSrfitvS5T+FQiVh8aPLHohXIZbuKP4imKk=,tag:zfH2lXWAXb7elbxY7CJXtw==,type:str]
kind: ENC[AES256_GCM,data:z9x83IXWJHoKgw==,iv:nnToCk7KnZ01XjbOIhzqdjxdp1zpnNYnb/RsHMfyKOc=,tag:o2Rtk0O1be2hkrb/Mz1iOQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BjcdN+OrLikUH8SSMX0dgDN5YiebIitqRw==,iv:Y91sxblQxnPZ9RHFaWdVPl8S21LtLKMA1HCEJ/v0dVo=,tag:NdDcdKQt63VJl3+fxqyraA==,type:str]
    namespace: ENC[AES256_GCM,data:3+1/EDtQYxrTIxt7,iv:IlN1i1SiaciFzGmfqARdzKiLJ0RMhQacDWKfk6Tt0zY=,tag:0VqemIKDupoavhUsl0xJGw==,type:str]
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:l2gj0VnoJe1jKRkfZ2LCljDPOvCWxDkuzBjH,iv:Pv/1pxPPrO7+7OigSuuEFlpl9CrPvCrifhfejm8XkYg=,tag:Jdun0ibqowunakE1/UmCow==,type:str]
          labels:
            app: ENC[AES256_GCM,data:N9HMm/Hm/1DKGKsZ,iv:YmSpC2XY+YpjO4W1EUBuizj0eY8/bc33v9ZspNQj0Yk=,tag:Cq2IC/MHSUQvAC26W4Kv3g==,type:str]
          stringData:
            api-token: ENC[AES256_GCM,data:UaqxfqmE1eVYZUNzf/Bl8dz57FmyM6kgasLBIsicaXvc1Mu8bXi1YQ==,iv:nvqlqRAqX76M7MT2SGJ8LqBtlnCWIxW9xkZa/0/2RzY=,tag:Qja49QJmL9eEtj5jlOvQfA==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQjFXNEwrVC90R3R0ci9Q
            QmhKTUUyVGhNQjBDOTE3dE16VzN6ZTYveVVRCmZsU3F3aXZHbDZmZ2M3QWhYbkhm
            ZnZoOXBLTm5KM1pyVEROSXFDZ1MxbDgKLS0tIEplamNDcFQ0SDB4Z1hmNVRKbStn
            Q01VbmZ0VHltTVZKcVd2cFdKellFZ2MK5gSUrvcSotHtWzX32fWpGQgLCC0zVGzL
            LBeYhdTfduOYdC5+cb1MvOZeoQpwh36xk0z9HiuRyopQSh6hSEVplw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T15:40:09Z"
    mac: ENC[AES256_GCM,data:GJB6rdergzP3J9TTu9SP7slthcNZx+6UyarlmMtR8N/G5BAsRAQ67P61JXPlz8TdFcaVtXgKhOP0q/DjfyxbBoU1aaPqokZnaXQq570wFrGyjNJcgbUYerWdZJc9U5Yzx1SR3FklGXq/GwgIFdQO624toB86muAtN/fBlAifkQA=,iv:j3J0QLxwAg/7sGr7DQTCehmCBpOSBDSplVrUKsH7M3w=,tag:/DNdEYvnVdU8pDr2ShoyNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
