apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-token-sops
    namespace: cert-manager
spec:
    secretTemplates:
        - name: cloudflare-api-token-secret
          labels:
            app: cert-manager
          stringData:
            api-token: ENC[AES256_GCM,data:+kLvr8H/ylZY4ni9syyxl+QhPlAH92GeCD2EoE97R0VO2Ilo6N0OxA==,iv:CJeS8dExrYYaPAbgbIIDVV9bY3tHlFWj4VS2fi96ICE=,tag:4XQxaVFdJLAv3bnzMxYbmw==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYmw1MURIV0VsR0dpQ1Rl
            UU5Nc201TUMwM1htOGpBK0lvbGdkOVNJK1dJCnh5dWJ5azhqbGxXSWN6eHVTb1Jz
            VnhLdVFHb0xxVTlBdFdVdUhMZ2p4S2MKLS0tIHVUb1BxVUNlbHhvUFNYelNWcVVI
            MHZxOS9lVHFma0NUTW5MakkvekxFYkkKGEMMW7tn8D/o7uuw1N1RA/xVSzcUqKHB
            FM6rPIuWa5ms1DAQdhO6a5KJLSsfy7P4aaez3hOT1iD3eUpe4MgUKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T16:44:58Z"
    mac: ENC[AES256_GCM,data:YENCxfldB4lIONJiZPp60mlIuafrxPrh+Eo4H0eQPaTQmvjayZeYlxaFowDQSK+j8mtt0T9HrimotWNdxtP7s1ZUjWpdDfj76ga6Ssw/hgL4YE6A/xK0BP0Lh68IWsc4T2hd6FH8qtFNFq7LBgk0lC57qT4O356oNuKRVwDsirk=,iv:NMFEdpOHrTW4U2Tm1iItbBmqQDL9q/h3VFGB/lOQNLg=,tag:/K9aloXrJTboAf/N4p1HKA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
