apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pihole-secrets-sops
    namespace: pihole
spec:
    secretTemplates:
        - name: pihole-password
          labels:
            app: pihole
          stringData:
            password: ENC[AES256_GCM,data:Dbs/tMv8opkfXTVyiXb1J9hoBh+v,iv:nt+Aso+mPUsKPKxufyLECHizcxZ5FFVNY/xxsGiL2Fs=,tag:IjO6/gnwaCTLp2STVDvEbA==,type:str]
sops:
    age:
        - recipient: age1gdp9htuaff9js8n4vl5y2z9nq39cctn9v2dae2v98hfh5fxs23cscu987d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMG1ZWDRrQ2hhM1VOcjUx
            NkdJUzQ2RlRtTzdsd2NKbzh1SUVYelphQzN3Ck9YMU5UWjFjeGhObFU2eUdZand4
            b2JJdUd3aEpkdW9HZERxeWpjSnZJR0kKLS0tIDkwVVUvZUQvNjF3UEZVN0I1ZlQv
            UG83SmRpblNrcjg4S3BFbDQzUWx6Y1EK3IWjql5H9Z0LyLV9Z9xXXv5T6qtdPLKg
            LiT189wka/L+7dAn+L5y5CPh9hEzOUaHK9LuHjO5kp5yfaiHlOqrPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T16:49:51Z"
    mac: ENC[AES256_GCM,data:Hs7K1MTrf+Kx9RXto+KaJFvDdw8P2sADvnQ4CTQfOWbe5PG9URSdiJAXHmWYbt1D4IXLsP7YGgIhf3H/1YzKfiKSJNDmZ2U4WKwKiSEjmEtkUS5BYMdmSfGo/bNW7sreN678q5J7izBFup44OTEH/5wNMeGxosBQpKCWWjwK5p4=,iv:4XeqcxIgFozvaBBHn9hBLQeN51AZzhnxDvHzeaJN6OI=,tag:szPO76YaImB7b1f7EvmUBg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
